workflows:
  android-build:
    name: Bubble Shooter 3D Build Pipeline
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Setup SDK
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make Gradle executable
        script: chmod +x gradlew

      - name: Clean
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - princearabdurrahman57@gmail.com
